#!/bin/sh

while ! mysqladmin ping -h"mariadb" --silent; do
    sleep 1
done

wp config create --dbname=wordpress --dbuser=root --dbpass=example --dbhost=mariadb
wp db create
wp core install --url=localhost --title="Louis-Marie Matthews's Blog" --admin_user=matthewslouismarie --admin_password=example --admin_email=matthewslouismarie@gmail.com
wp plugin install wordpress-importer --activate
cd /var/www/html/wp-content/themes/lblog/docker
wp import louis-mariematthews039sblog.wordpress.2018-05-26.xml --authors=create
wp post create --post_type=page --post_name=portfolio --post_status=publish
wp theme activate lblog

sudo apache2-foreground